api_platform:
  title: application_Resto 
  version: 1.0.0

  formats:
    json: ['application/json']

  patch_formats:
    json: ['application/merge-patch+json']

  docs_formats:
    jsonld: ['application/ld+json']
    jsonopenapi: ['application/vnd.openapi+json']
    html: ['text/html']

  defaults:
    stateless: false
    extra_properties:
      standard_put: false
      doctrine:
        orm:
          eager_loading:
            enabled: false  # <--- désactive l’eager loading automatique
            max_joins: 100  # cette ligne n'a plus d'effet tant que enabled est à false

  use_symfony_listeners: true
