framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will be started on demand.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    rate_limiter:
        api_limiter:
            policy: 'fixed_window'
            limit: 10
            interval: '1 minute'

    cache:
        pools:
            cache.rate_limiter:
                adapter: cache.adapter.redis