name: resto_app
description: Application client pour restaurant

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  mobile_scanner: ^7.1.3   # Remplace qr_code_scanner
  image_picker: ^1.0.4
  flutter_animate: ^4.1.1+1

  shared_preferences: ^2.2.2
  google_fonts: ^6.3.1
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
